lib/scaffold/config/routes.rb
def create_routes(router)
  router.draw do

    root to: 'bands#index'

    resource :sessions, only: [:new, :create, :destroy]

    resources :users, only: [:show, :new, :create]

    resources :bands do
      collection do
        get :json
      end
      resources :albums, only: [:new]
    end

    resources :albums, only: [:show, :create, :edit, :update, :destroy] do
      resources :tracks, only: [:new]
    end

    resources :tracks, only: [:show, :create, :edit, :update, :destroy,]

    resources :notes, only: [:create, :destroy]
  end

end

lib/scaffold/app/models/album.rb
class Album < ApplicationModel
  belongs_to :band
  has_many :tracks
  
  validates :band, presence: true
  validates :name, presence: true
  validates :year, presence: true

  after_initialize :set_defaults

  def set_defaults
    self.live ||= false
  end
end

lib/scaffold/app/models/application_model.rb
require_relative '../../lib/model/model_base'

class ApplicationModel < ModelBase

end 

lib/scaffold/app/models/band.rb
# require_relative '../lib/sql_object'

class Band < ApplicationModel
  validates :name, presence: true, uniqueness: true

  has_many :albums
end 

lib/scaffold/app/models/note.rb
class Note < ApplicationModel

  validates :content, presence: true

  belongs_to :user
  belongs_to :track
end

lib/scaffold/app/models/track.rb
class Track < ApplicationModel

  validates :lyrics, presence: true
  validates :name, presence: true
  validates :ord, presence: true

  belongs_to :album

  has_one :band,
    through: :album,
    source: :band

  has_many :notes

  after_initialize :set_defaults

  def set_defaults
    self.bonus ||= false
  end
end

lib/scaffold/app/models/user.rb
require 'bcrypt'

class User < ApplicationModel
  validates :username, presence: true, class: String, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true, uniqueness: true

  has_many :notes

  after_initialize :ensure_token
  
  attr_reader :password
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end
  
  def self.generate_token
    SecureRandom::urlsafe_base64
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def ensure_token
    self.session_token ||= User.generate_token
  end
  
  def reset_token!
    self.session_token = User.generate_token
    self.save!
    self.session_token
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

lib/scaffold/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      @band = @album.band
      flash.now[:errors] = @album.errors
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])

    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end

  private

  def album_params
    params.require(:album).permit(:band_id, :live, :name, :year)
  end

  before_action :ensure_login, except: [:index]
end

lib/scaffold/app/controllers/application_controller.rb
require_relative '../../lib/controller/controller_base'

class ApplicationController < ControllerBase

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def ensure_login
    unless logged_in?
      flash[:errors] = ['must be logged in']
      redirect_to new_sessions_url
      
      true
    else
      false
    end
  end

  def ensure_logout
    if logged_in?
      flash[:errors] = ['already logged in']
      redirect_to bands_url

      true
    else
      false
    end
  end

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_token!
  end

  def logout
    current_user.reset_token!
    session[:session_token] = nil
    @current_user = nil
  end

  def logged_in?
    !!current_user
  end
end

lib/scaffold/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  protect_from_forgery
  
  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  def json
    @bands = Band.all
  end

  private
  
  def band_params
    params.require(:band).permit(:name)
  end

  before_action :ensure_login
end

lib/scaffold/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  protect_from_forgery
  
  def create
    note = Note.new(note_params)
    note.user_id = current_user.id
    note.save
    flash[:errors] = note.errors
    
    redirect_to track_url(note.track_id)
  end
  
  def destroy
    note = Note.find(params[:id])
    note.destroy
    redirect_to track_url(note.track_id)
  end
  
  private
  
  def note_params
    params.require(:note).permit(:content, :track_id)
  end

  before_action :ensure_login, only: [:create, :destroy]
end

lib/scaffold/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  protect_from_forgery

  def new
    @user = User.new
  end

  def create
    username = session_params[:username]
    password = session_params[:password]

    @user = User.find_by_credentials(username, password)
    if @user
      login(@user)
      redirect_to root_url
    else
      flash.now[:errors] = ['invalid username/password']
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_sessions_url
  end

  private

  def session_params
    params.require(:user).permit(:username, :password)
  end

  before_action :ensure_logout, only: [:new, :create]
end

lib/scaffold/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  protect_from_forgery
  
  def show
    @track = Track.find(params[:id])
    render :show
  end

  def new
    @album = Album.find(params[:album_id])
    @track = Track.new(album_id: params[:album_id])
    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      @album = @track.album
      flash.now[:errors] = @track.errors
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update_attributes(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to album_url(@track.album_id)
  end

  private

  def track_params
    params.require(:track).permit(:album_id, :bonus, :lyrics, :name, :ord)
  end

  before_action :ensure_login, except: [:index]
end

lib/scaffold/app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to bands_url
    else
      flash.now[:errors] = @user.errors
      render :new
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  before_action :ensure_logout, only: [:new, :create]
  before_action :ensure_login, only: [:index, :show, :destroy]
end

lib/scaffold/app/views/albums_controller/edit.html.erb
<h1 class='page-header'>Edit <%= @album.name %></h1>

<form class='form' action="<%= album_url(@album) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label for='album-name'>Name</label>
    <input id='album-name' type="text" name="album[name]" value="<%= @album.name %>">
  </p>

  <p>
    <label for='album-band'>Band</label>
    <select id='album-band' name="album[band_id]">
        <% Band.all.each do |band| %>
            <option
                <%= "selected" if @album.band_id == band.id %>
                value="<%= band.id %>">
                <%= band.name %>
            </option>
        <% end %>
    </select>
  </p>

  <p>
    <label for="album_live_t">Live</label>
    <input
      type="radio"
      name="album[live]"
      value="t"
      id="album_live_t"
      <%= "checked" if @album.live %>>
    <label for="album_live_f">Studio</label>
    <input
      type="radio"
      name="album[live]"
      value="f"
      id="album_live_f"
      <%= "checked" if !@album.live %>>
  </p>

  <p>
    <label for='album-year'>Year</label>
    <input id='album-year' type="number" name="album[year]" value="<%= @album.year %>">
  </p>

  <input type="submit" value="Update Album!">
</form>

lib/scaffold/app/views/albums_controller/new.html.erb
<h1 class='page-header'>New <%= @band.name %> Album!</h1>

<form class='form' action="<%= albums_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label for='album-name'>Name</label>
    <input id='album-name' type="text" name="album[name]" value="<%= @album.name %>">
  </p>

  <p>
    <label for='album-band'>Band</label>
    <select id='album-band' name="album[band_id]">
        <% Band.all.each do |band| %>
            <option
                <%= "selected" if @album.band_id == band.id %>
                value="<%= band.id %>">
                <%= band.name %>
            </option>
        <% end %>
    </select>
  </p>

  <p>
    <label for="album_live_t">Live</label>
    <input
      type="radio"
      name="album[live]"
      value="t"
      id="album_live_t"
      <%= "checked" if @album.live %>>
    <label for="album_live_f">Studio</label>
    <input
      type="radio"
      name="album[live]"
      value="f"
      id="album_live_f"
      <%= "checked" if !@album.live %>>
  </p>

  <p>
    <label for='album-year'>Year</label>
    <input id='album-year' type="number" name="album[year]" value="<%= @album.year %>">
  </p>

  <input type="submit" value="Create Album!">
</form>

lib/scaffold/app/views/albums_controller/show.html.erb
<h1 class='page-header'><%= @album.name %></h1>

<% if @album.tracks.length > 0 %>
<ul class='main-list'>
  <% @album.tracks.each do |track| %>
    <li><a href="<%= track_url(track) %>"><p><%= track.name %></p></a></li>
  <% end %>
</ul>
<% else %>
  <p>This album has no tracks... yet!</p> 
<% end %>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= new_album_tracks_url(@album) %>">New track</a></li>
  <li><a class='button' href="<%= edit_album_url(@album) %>">Edit album</a></li>
  <li>
    <form action="<%= album_url(@album) %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
      <input type="submit" value="Destroy Album">
    </form>
  </li>
  <li><a class='button' href="<%= band_url(@album.band) %>">Back to <%= @album.band.name %></a></li>
</ul>

lib/scaffold/app/views/bands_controller/edit.html.erb
<h1 class='page-header'>Edit <%= @band.name %></h1>

<form class='form' action="<%= band_url(@band) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label for='band-name'>Name</label>
    <input id='band-name' type="text" name="band[name]" value="<%= @band.name %>">
  </p>

  <input type="submit">
</form>

lib/scaffold/app/views/bands_controller/index.html.erb
<h1 class='page-header'>Bands</h1>

<ul class='main-list'>
  <% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"><p><%= band.name %></p></a></li>
  <% end %>
</ul>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= new_bands_url %>" >New band</a></li>
</ul>

lib/scaffold/app/views/bands_controller/new.html.erb
<h1 class='page-header'>New Band!</h1>

<form class='form' action="<%= bands_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label for='band-name'>Name</label>
    <input id='band-name' type="text" name="band[name]" value="<%= @band.name %>">
  </p>

  <input type="submit">
</form>

lib/scaffold/app/views/bands_controller/show.html.erb
<h1 class='page-header'><%= @band.name %></h1>

<h4 class='sub-header'>Albums</h4>

<% if @band.albums.length > 0 %>
  <ul class='main-list'>
  <% @band.albums.each do |album| %>
    <li><a href="<%= album_url(album) %>"><p><%= album.name %></p></a></li>
  <% end %>
  </ul>
<% else %>
  <p>This band has no albums... yet!</p>
<% end %>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= new_band_albums_url(@band) %>">New album</a></li>
  <li><a class='button' href="<%= edit_band_url(@band) %>">Edit Band</a></li>
  <li>
    <form action="<%= band_url(@band) %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
      <input type="submit" value="Destroy Band">
    </form>
  </li>
  <li><a class='button' href="<%= bands_url %>">All bands</a></li>
</ul>

lib/scaffold/app/views/sessions_controller/new.html.erb
<h2 class='page-header'>Sign-in</h2>

<a class='button' href=<%= new_users_url %> >Go to Sign-up!</a>

<form class='form' action="<%= sessions_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label for='new-user-email'>Username</label>
    <input id='new-user-email' type="text" name="user[username]">
  </p>

  <p>
    <label for='new-user-password'>Password</label>
    <input id='new-user-password' type="password" name="user[password]">
  </p>

  <input type="submit">
</form>

lib/scaffold/app/views/tracks_controller/edit.html.erb
<h1 class='page-header'>Edit <%= @track.name %></h1>

<form class='form' action="<%= track_url(@track) %>" method="POST" %>
  <input type="hidden" name="_method" value="PATCH">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

<p>
  <label for='track-name'>Name</label>
  <input id='track-name' type="text" name="track[name]" value="<%= @track.name %>">
</p>

<p>
<label for='track-album'>Album</label>
  <select id='track-album' name="track[album_id]">
    <% Album.all.each do |album| %>
      <option
        <%= "selected" if @track.album_id == album.id %>
        value="<%= album.id %>">
        <%= album.name %>
      </option>
    <% end %>
  </select>
</p>

<p>
  <label>Ord
  <input type="number" name="track[ord]" value="<%= @track.ord %>">
  </label>
</p>

<p>
  <label for="track_bonus_f">Standard</label>
  <input
    type="radio"
    name="track[bonus]"
    value="f"
    id="track_bonus_f"
    <%= "checked" if !@track.bonus %>>
  <br>
  <label for="track_bonus_t">Bonus</label>
  <input
    type="radio"
    name="track[bonus]"
    value="t"
    id="track_bonus_t"
    <%= "checked" if @track.bonus %>>
</p>

<p>
  <label for="track_lyrics">Lyrics</label><br>
  <textarea id="track_lyrics"
    rows="10" cols="40"
    name="track[lyrics]"><%= @track.lyrics %></textarea>
</p>

  <input type="submit">
</form>

lib/scaffold/app/views/tracks_controller/new.html.erb
<h1 class='page-header'>New <%= @album.name %> Track</h1>

<form class='form' action="<%= tracks_url %>" method="POST" %>
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

<p>
  <label for='track-name'>Name</label>
  <input id='track-name' type="text" name="track[name]" value="<%= @track.name %>">
</p>

<p>
<label for='track-album'>Album</label>
  <select id='track-album' name="track[album_id]">
    <% Album.all.each do |album| %>
      <option
        <%= "selected" if @track.album_id == album.id %>
        value="<%= album.id %>">
        <%= album.name %>
      </option>
    <% end %>
  </select>
</p>

<p>
  <label>Ord
  <input type="number" name="track[ord]" value="<%= @track.ord %>">
  </label>
</p>

<p>
  <label for="track_bonus_f">Standard</label>
  <input
    type="radio"
    name="track[bonus]"
    value="f"
    id="track_bonus_f"
    <%= "checked" if !@track.bonus %>>
  <br>
  <label for="track_bonus_t">Bonus</label>
  <input
    type="radio"
    name="track[bonus]"
    value="t"
    id="track_bonus_t"
    <%= "checked" if @track.bonus %>>
</p>

<p>
  <label for="track_lyrics">Lyrics</label><br>
  <textarea id="track_lyrics"
    rows="10" cols="40"
    name="track[lyrics]"><%= @track.lyrics %></textarea>
</p>

  <input type="submit">
</form>

lib/scaffold/app/views/tracks_controller/show.html.erb
<h1 class='page-header'><%= @track.name %></h1>

<%= @track.lyrics %>

<h4 class='sub-header'>New Note</h4>

<form class='form' action="<%= notes_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="note[track_id]" value="<%= @track.id %>">

  <p>
    <label for="note_content">Content</label>
    <textarea id="note_content"
      rows="7" cols="30"
      name="note[content]"></textarea>
  </p>

  <input type="submit">
</form>


<h4 class='sub-header'>Notes</h4>

<% @track.notes.each do |note| %>
  <div class='note-item'>
    <p><%= note.content %></p>
    <div class='note-item-info'>
      <p>Authored by: <%= note.user.username %></p>

      <% if note.user_id == current_user.id %>
        <form action="<%= note_url(note) %>" method="POST">
          <input type="hidden" name="_method" value="DELETE">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
          <input type="submit" value="Destroy Note">
        </form>
      <% end %>
    </div>
  </div>
<% end %>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= edit_track_url(@track) %>">Edit Track</a></li>
  <li>
    <form action="<%= track_url(@track) %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
      <input type="submit" value="Destroy Track">
    </form>
  </li>
  <li><a class='button' href="<%= album_url(@track.album) %>"><%= @track.album.name %></a></li>
</ul>

lib/scaffold/app/views/users_controller/new.html.erb
<h1 class='page-header'>New User</h1>

<a class='button' href=<%= new_sessions_url %> >Go to sign-in</a>

<form class='form' action="<%= users_url %>" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label for='new-user-email'>Username</label>
    <input id='new-user-email' type="text" name="user[username]">
  </p>

  <p>
    <label for='new-user-password'>Password</label>
    <input id='new-user-password' type="password" name="user[password]">
  </p>

  <input type="submit" value="Submit">
</form>

lib/scaffold/app/views/users_controller/show.html.erb
<h1 class='page-header'>User Profile</h1>
<p>
  Email: <%= current_user.email %>
</p>